config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :exercises
  end
  root 'workouts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:workout].permit(:nome, :series, :repeticoes))

    redirect_to workout_path(@workout)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  def index 
    @workouts = Workout.all.order("created_at DESC")
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create 
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit 
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  private 

  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercises.html.haml
%p 
  = exercise.nome

%p 
  = exercise.series

%p 
  = exercise.repeticoes

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|

  = f.input :name, input_html: { class: "form-control" }

  = f.input :sets, input_html: { class: "form-control" }

  = f.input :reps, input_html: { class: "form-control" }
  
  = f.button :submit

app/views/layouts/application.html.haml
#app_page
!!!
%html
%head
  %title Log de Treinos
  = stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag   'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = csp_meta_tag
%body
  %nav.navbar.navbar-default
    .container
      .navbar-header
        = link_to "Log de Treinos", root_path, class: "navbar-brand"
      .nav.navbar-nav.navbar-right
        %div
        = link_to "Novo Treino ->", new_workout_path, class: "navbar navbar-link"

  .container
    = yield 

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
  = f.input :date, label: "Data do treino"
  = f.input :workout, label: "Qual treino você realizou?"
  = f.input :mood, label: "Como você estava se sentindo no treino?"
  = f.input :length, label: "Quanto tempo durou o treino?"
  
  = f.button :submit, value: "Criar Treino"

app/views/workouts/edit.html.haml
%h1 Edição de Treino

= render "form"
= link_to "Cancelar", root_path, class: "btnCancelar"

app/views/workouts/index.html.haml
#index_workouts
  - @workouts.each do |workout|
    %h2= link_to workout.date.strftime("%A %B %m %Y"), workout
    %h3
      %span Treino:
      = workout.workout 
    
    %div
      = link_to "Editar", edit_workout_path(@workouts), class: "btnEditar"

app/views/workouts/new.html.haml
#html_novoTreino
  %h1 Novo Treino

  = render "form"

  = link_to "Cancelar", root_path, class: "btnCancelar"

app/views/workouts/show.html.haml
#workout
  %h2 Treino selecionado

  %h3 
    %span Data:
    = @workout.date
  %h3
    %span Treino:
    = @workout.workout
  %h3 
    %span Humor:
    = @workout.mood
  %h3 
    %span Duração:
    = @workout.length

#exercises
  %h2 Treinos
  = render @workout.exercises

  %h3 Adicionar um treino
  = render "exercises/form"

#botoes

= link_to "Voltar", root_path, class: "btnVoltar"
= link_to "Editar", edit_workout_path(@workout), class: "btnEdit"
= link_to "Deletar", workout_path(@workout), method: :delete, data: { confirm: "Tem certeza de que deseja deletar?" }, class: "btnDelete"